version: '3'

services:
  nginx:
    container_name: nginx
    build: requirements/nginx
    image: nginx
    depends_on:
      - wordpress
    ports:
      - 443:443
    networks:
      - inception_network
    volumes:
      - wp_data:/var/www/html
    restart: always

  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    image: mariadb
    env_file:
      - .env
    ports:
      - 3036:3036
    networks:
      - inception_network
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    image: wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    ports:
      - 9000:9000
    networks:
      - inception_network
    volumes:
      - db_data:/var/lib/mysql
    restart: always

networks:
  inception_network:

volumes:
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/fluchten/data/wp
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/fluchten/data/db
