version: '3'

services:
  my-nginx:
    build: requirements/nginx
    image: my-nginx
    ports:
      - 443:443
    networks:
      - inception
    restart: always

  my-mariadb:
    build: requirements/mariadb
    image: my-mariadb
    ports:
      - 3036:3036
    networks:
      - inception
    env_file:
      - .env
    restart: always

networks:
  inception:
