version: '3'

services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - docker-network
    restart: always

  nginx:
    container_name: nginx
    build: 
      context: ./requirements/nginx
    depends_on:
      - wordpress
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html
    networks:
      - docker-network
    restart: always

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    ports:
      - 9000:9000
    volumes:
      - wordpress:/var/www/html
    networks:
      - docker-network
    restart: always

networks:
  docker-network:
    driver: bridge

volumes:
  mariadb:
    driver: local
    driver_opts:
      type : bind
      o: bind
      device: /home/fluchten/data/mariadb
  wordpress:
    driver: local
    driver_opts:
      type : bind
      o: bind
      device: /home/fluchten/data/wordpress
